name: posts
description: "Share ideas with the world."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.16.0
  image_picker: ^1.0.7
  xid: ^1.1.2
  firebase_storage: ^11.7.0
  modal_progress_hud_nsn: ^0.5.0
  intl: ^0.17.0
  provider: ^6.1.2
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#F7F4EE"
  image: "images/rows.png"

flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  image_path: "images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "images/icon_foreground.png"
  adaptive_icon_background: "#1D3630" 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true

  assets:
    - images/vector.svg
    - images/small-logo.svg
    - images/googleLogo.svg
    - images/image.svg
    - images/filled-home.svg
    - images/filled-search.svg
    - images/line-search.svg
    - images/line-home.svg
    - images/plus.svg
    - images/comment.svg
    - images/heart.svg
    - images/options.svg
    - images/placeholder.png
    - images/filled-heart.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #