name: posts
description: "Share ideas with the world."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.16.0
  image_picker: ^1.0.7
  xid: ^1.1.2
  firebase_storage: ^11.7.0
  modal_progress_hud_nsn: ^0.5.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/vector.svg
    - images/small-logo.svg
    - images/googleLogo.svg
    - images/image.svg
    - images/filled-home.svg
    - images/filled-search.svg
    - images/line-search.svg
    - images/line-home.svg
    - images/plus.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #